<a href="https://colab.research.google.com/github/abhi311295/Multi-class-Classification-with-XGBoost/blob/main/Multi_class_classifier_Iris_XGBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
#importing the Dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score

In [8]:
#Importing the dataset
df = pd.read_csv('Iris.csv')

In [9]:
#first initial rows of the dataset
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
#shape of the dataset 
df.shape

(150, 6)

In [15]:
#checking the null values 
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [22]:
#spilling the data and the target 
x = df.iloc[:,:4].values
y = df.iloc[:,5].values 

In [27]:
#label encoding 
Encoder = LabelEncoder()
y = Encoder.fit_transform(y)

In [30]:
#train test split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=2)
print (x.shape ,x_train.shape ,x_test.shape )

(150, 4) (120, 4) (30, 4)


In [35]:
#Model training 
xgb_model = xgb.XGBClassifier()
xgb_model.fit(x_train,y_train)

XGBClassifier(objective='multi:softprob')

In [39]:
#prediction of the data 
x_test_predict = xgb_model.predict(x_test)
x_test_predict

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2])

In [43]:
#confusion matrix 
cnf_mat= confusion_matrix(y_test,x_test_predict)
print (cnf_mat)

[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]


In [50]:
#accuracy score 
acc_score = accuracy_score(y_test,x_test_predict)
print (acc_score*100)

100.0
